#!/bin/sh

amixer sset Master unmute
amixer sset Headphones unmute
amixer sset Speaker unmute

amixer sset Master 100%

# PYTHON THREE FOREVER BABY!
while [ 1 ]
do
  clear
  printf "SNAKEWARE READY.\n\n"
  PYTHONSTARTUP=/usr/share/snakeware/startup.py /usr/bin/python3
done
